# Generated by Django 2.0.7 on 2018-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='production_type',
            field=models.CharField(choices=[('live action', 'Live-action'), ('animated', 'Animated'), ('anime', 'Anime')], default='live action', max_length=12),
        ),
        migrations.AlterField(
            model_name='show',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added'),
        ),
        migrations.AlterField(
            model_name='show',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='show',
            name='type',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Series')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='show',
            name='watch_state',
            field=models.CharField(blank=True, choices=[('N', 'Not Started'), ('W', 'Watching'), ('D', 'Done'), ('L', 'Deferred'), ('X', 'Dropped')], max_length=1),
        ),
    ]
